-- Phase 2 order-submission reliability primitives.
--
-- This migration is intentionally additive. It does not enable RLS or revoke
-- the legacy anonymous grants on the two Facebook order tables. Those changes
-- must happen only after every form and admin consumer has moved to the
-- server-owned endpoints and the cutover audit has passed.

alter table public."New Facebook Orders"
  add column if not exists submission_id uuid;

alter table public."New PRE Facebook Orders"
  add column if not exists submission_id uuid,
  add column if not exists submission_status text not null default 'draft',
  add column if not exists submission_updated_at timestamptz not null default now();

alter table public.pending_facebook_orders
  add column if not exists submission_id uuid,
  add column if not exists submission_status text not null default 'draft',
  add column if not exists request_fingerprint text,
  add column if not exists preorder_facebook_u uuid,
  add column if not exists route_kind text,
  add column if not exists updated_at timestamptz not null default now();

alter table public.xendit_payments
  add column if not exists submission_id uuid,
  add column if not exists final_order_id bigint,
  add column if not exists attempt_id uuid;

update public."New PRE Facebook Orders"
set submission_status = case when submitted then 'completed' else 'draft' end
where submission_status is distinct from
  case when submitted then 'completed' else 'draft' end;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public."New PRE Facebook Orders"'::regclass
      and conname = 'new_pre_facebook_orders_submission_status_check'
  ) then
    alter table public."New PRE Facebook Orders"
      add constraint new_pre_facebook_orders_submission_status_check
      check (submission_status in (
        'draft',
        'payment_pending',
        'completed',
        'payment_failed'
      ));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.pending_facebook_orders'::regclass
      and conname = 'pending_facebook_orders_submission_status_check'
  ) then
    alter table public.pending_facebook_orders
      add constraint pending_facebook_orders_submission_status_check
      check (submission_status in (
        'draft',
        'payment_pending',
        'completed',
        'payment_failed'
      ));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.pending_facebook_orders'::regclass
      and conname = 'pending_facebook_orders_route_kind_check'
  ) then
    alter table public.pending_facebook_orders
      add constraint pending_facebook_orders_route_kind_check
      check (
        route_kind is null
        or route_kind in ('default', 'facebook_uuid', 'subscriber_psid')
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.xendit_payments'::regclass
      and conname = 'xendit_payments_final_order_id_fkey'
  ) then
    alter table public.xendit_payments
      add constraint xendit_payments_final_order_id_fkey
      foreign key (final_order_id)
      references public."New Facebook Orders" (id)
      on delete set null;
  end if;
end
$$;

create unique index if not exists
  new_facebook_orders_submission_id_key
  on public."New Facebook Orders" (submission_id)
  where submission_id is not null;

create unique index if not exists
  new_pre_facebook_orders_submission_id_key
  on public."New PRE Facebook Orders" (submission_id)
  where submission_id is not null;

create unique index if not exists
  pending_facebook_orders_submission_id_key
  on public.pending_facebook_orders (submission_id)
  where submission_id is not null;

create unique index if not exists
  xendit_payments_submission_id_key
  on public.xendit_payments (submission_id)
  where submission_id is not null;

create unique index if not exists
  xendit_payments_final_order_id_key
  on public.xendit_payments (final_order_id)
  where final_order_id is not null;

create table if not exists public.order_submission_events (
  id bigint generated by default as identity primary key,
  submission_id uuid,
  attempt_id uuid not null,
  stage text not null check (
    stage in (
      'validation',
      'upload',
      'save',
      'payment',
      'completion'
    )
  ),
  event_name text not null,
  route_kind text check (
    route_kind is null
    or route_kind in ('default', 'facebook_uuid', 'subscriber_psid')
  ),
  item_count integer check (item_count is null or item_count >= 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  release_sha text,
  error_code text,
  created_at timestamptz not null default now()
);

alter table public.order_submission_events enable row level security;
revoke all on table public.order_submission_events from public, anon, authenticated;
grant select, insert on table public.order_submission_events to service_role;
grant usage, select on sequence public.order_submission_events_id_seq to service_role;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'order-form-assets',
  'order-form-assets',
  true,
  3145728,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update
set
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.create_order_from_submission(
  p_submission_id uuid,
  p_order_data jsonb,
  p_preorder_facebook_u uuid default null
)
returns table (
  order_id bigint,
  order_number text,
  created boolean
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_order public."New Facebook Orders";
  v_existing public."New Facebook Orders";
begin
  if p_submission_id is null then
    raise exception using
      errcode = '22023',
      message = 'submission_id_required';
  end if;

  if p_order_data is null or jsonb_typeof(p_order_data) <> 'object' then
    raise exception using
      errcode = '22023',
      message = 'order_data_invalid';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_submission_id::text, 0)
  );

  select *
  into v_existing
  from public."New Facebook Orders"
  where submission_id = p_submission_id
  limit 1;

  if found then
    update public."New PRE Facebook Orders"
    set
      submitted = true,
      submission_status = 'completed',
      submission_updated_at = now()
    where submission_id = p_submission_id
       or (
         p_preorder_facebook_u is not null
         and "facebookU" = p_preorder_facebook_u
       );

    return query
    select
      v_existing.id,
      v_existing.order_number_text,
      false;
    return;
  end if;

  v_order := jsonb_populate_record(
    null::public."New Facebook Orders",
    p_order_data
      - 'id'
      - 'created_at'
      - 'submission_id'
      - 'order_number_text'
      - 'totalorderprice'
  );

  v_order.created_at := now();
  v_order.submission_id := p_submission_id;
  v_order.branch := coalesce(nullif(v_order.branch, ''), 'Cebu');
  v_order."DateOrdered" := coalesce(v_order."DateOrdered", current_date);
  v_order."copiedToList" := coalesce(v_order."copiedToList", false);
  v_order.hold := coalesce(v_order.hold, false);

  -- List only writable columns. This deliberately excludes the identity,
  -- generated order number, and created_at defaults, so future generated
  -- columns cannot be accidentally populated through a whole-row composite.
  insert into public."New Facebook Orders" (
    "facebookU",
    "DateOrdered",
    "DateEvent",
    "TimeEvent",
    "Name",
    contact,
    "Addres",
    "receiverName",
    "receiverContact",
    "orderNumber",
    "orderLink",
    "Product1",
    code1,
    "Message1",
    details1,
    quantity1,
    "Price1",
    "paymentOption",
    "Comment",
    "Product2",
    code2,
    message2,
    details2,
    quantity2,
    price2,
    "copiedToList",
    hold,
    "Candle",
    pic2,
    product3,
    code3,
    message3,
    details3,
    qty3,
    pic3,
    facebookname,
    numberproducts,
    branch,
    candle2,
    candle3,
    latitude,
    longitude,
    manychatlink,
    payment,
    subscriberid,
    submission_id
  )
  values (
    v_order."facebookU",
    v_order."DateOrdered",
    v_order."DateEvent",
    v_order."TimeEvent",
    v_order."Name",
    v_order.contact,
    v_order."Addres",
    v_order."receiverName",
    v_order."receiverContact",
    v_order."orderNumber",
    v_order."orderLink",
    v_order."Product1",
    v_order.code1,
    v_order."Message1",
    v_order.details1,
    v_order.quantity1,
    v_order."Price1",
    v_order."paymentOption",
    v_order."Comment",
    v_order."Product2",
    v_order.code2,
    v_order.message2,
    v_order.details2,
    v_order.quantity2,
    v_order.price2,
    v_order."copiedToList",
    v_order.hold,
    v_order."Candle",
    v_order.pic2,
    v_order.product3,
    v_order.code3,
    v_order.message3,
    v_order.details3,
    v_order.qty3,
    v_order.pic3,
    v_order.facebookname,
    v_order.numberproducts,
    v_order.branch,
    v_order.candle2,
    v_order.candle3,
    v_order.latitude,
    v_order.longitude,
    v_order.manychatlink,
    v_order.payment,
    v_order.subscriberid,
    p_submission_id
  )
  returning *
  into v_order;

  update public."New PRE Facebook Orders"
  set
    submission_id = p_submission_id,
    submitted = true,
    submission_status = 'completed',
    submission_updated_at = now()
  where (
      submission_id = p_submission_id
      or (
        p_preorder_facebook_u is not null
        and "facebookU" = p_preorder_facebook_u
      )
    )
    and (
      submission_id is null
      or submission_id = p_submission_id
    );

  return query
  select
    v_order.id,
    v_order.order_number_text,
    true;
end;
$$;

revoke execute on function public.create_order_from_submission(uuid, jsonb, uuid)
  from public, anon, authenticated;
grant execute on function public.create_order_from_submission(uuid, jsonb, uuid)
  to service_role;

create or replace function public.prepare_xendit_submission(
  p_submission_id uuid,
  p_order_data jsonb,
  p_request_fingerprint text,
  p_preorder_facebook_u uuid,
  p_route_kind text
)
returns table (
  pending_order_id uuid,
  final_order_id bigint,
  final_order_number text,
  created boolean
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_pending public.pending_facebook_orders;
  v_final public."New Facebook Orders";
  v_pre_submitted boolean;
  v_pre_submission_id uuid;
begin
  if p_submission_id is null then
    raise exception using
      errcode = '22023',
      message = 'submission_id_required';
  end if;

  if p_order_data is null or jsonb_typeof(p_order_data) <> 'object' then
    raise exception using
      errcode = '22023',
      message = 'order_data_invalid';
  end if;

  if nullif(p_request_fingerprint, '') is null then
    raise exception using
      errcode = '22023',
      message = 'request_fingerprint_required';
  end if;

  if p_route_kind is null
    or p_route_kind not in ('default', 'facebook_uuid', 'subscriber_psid')
  then
    raise exception using
      errcode = '22023',
      message = 'route_kind_invalid';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_submission_id::text, 0)
  );

  select *
  into v_final
  from public."New Facebook Orders"
  where submission_id = p_submission_id
  limit 1;

  if found then
    return query
    select
      null::uuid,
      v_final.id,
      v_final.order_number_text,
      false;
    return;
  end if;

  if p_preorder_facebook_u is not null then
    select submitted, submission_id
    into v_pre_submitted, v_pre_submission_id
    from public."New PRE Facebook Orders"
    where "facebookU" = p_preorder_facebook_u
    for update;

    if found
      and v_pre_submitted
      and v_pre_submission_id is distinct from p_submission_id
    then
      raise exception using
        errcode = '23505',
        message = 'preorder_already_submitted';
    end if;
  end if;

  select *
  into v_pending
  from public.pending_facebook_orders
  where submission_id = p_submission_id
  for update;

  if found then
    if v_pending.request_fingerprint is distinct from p_request_fingerprint then
      raise exception using
        errcode = '22023',
        message = 'submission_payload_conflict';
    end if;

    return query
    select
      v_pending.id,
      null::bigint,
      null::text,
      false;
    return;
  end if;

  insert into public.pending_facebook_orders (
    order_data,
    submission_id,
    submission_status,
    request_fingerprint,
    preorder_facebook_u,
    route_kind,
    updated_at
  )
  values (
    p_order_data,
    p_submission_id,
    'payment_pending',
    p_request_fingerprint,
    p_preorder_facebook_u,
    p_route_kind,
    now()
  )
  returning *
  into v_pending;

  update public."New PRE Facebook Orders"
  set
    submission_id = p_submission_id,
    submitted = false,
    submission_status = 'payment_pending',
    submission_updated_at = now()
  where p_preorder_facebook_u is not null
    and "facebookU" = p_preorder_facebook_u
    and (
      submission_id is null
      or submission_id = p_submission_id
    );

  return query
  select
    v_pending.id,
    null::bigint,
    null::text,
    true;
end;
$$;

revoke execute on function public.prepare_xendit_submission(
  uuid,
  jsonb,
  text,
  uuid,
  text
) from public, anon, authenticated;
grant execute on function public.prepare_xendit_submission(
  uuid,
  jsonb,
  text,
  uuid,
  text
) to service_role;

create or replace function public.record_xendit_invoice(
  p_submission_id uuid,
  p_pending_order_id uuid,
  p_attempt_id uuid,
  p_invoice_id text,
  p_external_id text,
  p_status text,
  p_amount numeric,
  p_payment_url text,
  p_expiry_date timestamptz,
  p_user_id uuid
)
returns public.xendit_payments
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_payment public.xendit_payments;
  v_pending public.pending_facebook_orders;
begin
  if p_submission_id is null
    or p_pending_order_id is null
    or nullif(p_invoice_id, '') is null
    or nullif(p_external_id, '') is null
    or p_amount is null
    or p_amount <= 0
  then
    raise exception using
      errcode = '22023',
      message = 'payment_record_invalid';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_submission_id::text, 0)
  );

  select *
  into v_pending
  from public.pending_facebook_orders
  where id = p_pending_order_id
    and submission_id = p_submission_id
  for update;

  if not found then
    raise exception using
      errcode = 'P0002',
      message = 'pending_order_not_found';
  end if;

  select *
  into v_payment
  from public.xendit_payments
  where submission_id = p_submission_id
  for update;

  if found then
    if v_payment.xendit_invoice_id <> p_invoice_id
      or v_payment.xendit_external_id <> p_external_id
      or v_payment.amount <> p_amount
    then
      raise exception using
        errcode = '22023',
        message = 'payment_invoice_conflict';
    end if;

    return v_payment;
  end if;

  insert into public.xendit_payments (
    order_id,
    xendit_invoice_id,
    status,
    amount,
    payment_link_url,
    expiry_date,
    xendit_external_id,
    user_id,
    submission_id,
    attempt_id
  )
  values (
    p_pending_order_id::text,
    p_invoice_id,
    p_status,
    p_amount,
    p_payment_url,
    p_expiry_date,
    p_external_id,
    coalesce(p_user_id, '00000000-0000-0000-0000-000000000000'::uuid),
    p_submission_id,
    p_attempt_id
  )
  returning *
  into v_payment;

  update public.pending_facebook_orders
  set
    submission_status = 'payment_pending',
    updated_at = now()
  where id = p_pending_order_id;

  return v_payment;
end;
$$;

revoke execute on function public.record_xendit_invoice(
  uuid,
  uuid,
  uuid,
  text,
  text,
  text,
  numeric,
  text,
  timestamptz,
  uuid
) from public, anon, authenticated;
grant execute on function public.record_xendit_invoice(
  uuid,
  uuid,
  uuid,
  text,
  text,
  text,
  numeric,
  text,
  timestamptz,
  uuid
) to service_role;

create or replace function public.record_xendit_payment_status(
  p_submission_id uuid,
  p_invoice_id text,
  p_status text,
  p_payment_method text default null,
  p_paid_amount numeric default null,
  p_paid_at timestamptz default null
)
returns public.xendit_payments
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_payment public.xendit_payments;
  v_pending_state text;
begin
  if p_submission_id is null or nullif(p_invoice_id, '') is null then
    raise exception using
      errcode = '22023',
      message = 'payment_status_reference_invalid';
  end if;

  if p_status is null
    or p_status not in ('PENDING', 'PAID', 'SETTLED', 'EXPIRED', 'FAILED')
  then
    raise exception using
      errcode = '22023',
      message = 'payment_status_invalid';
  end if;

  if p_status in ('PAID', 'SETTLED') then
    raise exception using
      errcode = '22023',
      message = 'paid_status_requires_finalization';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_submission_id::text, 0)
  );

  update public.xendit_payments
  set
    status = p_status,
    payment_method = coalesce(p_payment_method, payment_method),
    paid_amount = coalesce(p_paid_amount, paid_amount),
    paid_at = coalesce(p_paid_at, paid_at),
    updated_at = now()
  where submission_id = p_submission_id
    and xendit_invoice_id = p_invoice_id
  returning *
  into v_payment;

  if not found then
    raise exception using
      errcode = 'P0002',
      message = 'payment_record_not_found';
  end if;

  v_pending_state := case
    when p_status in ('EXPIRED', 'FAILED') then 'payment_failed'
    else 'payment_pending'
  end;

  update public.pending_facebook_orders
  set
    submission_status = v_pending_state,
    updated_at = now()
  where submission_id = p_submission_id;

  update public."New PRE Facebook Orders"
  set
    submitted = false,
    submission_status = v_pending_state,
    submission_updated_at = now()
  where submission_id = p_submission_id;

  return v_payment;
end;
$$;

revoke execute on function public.record_xendit_payment_status(
  uuid,
  text,
  text,
  text,
  numeric,
  timestamptz
) from public, anon, authenticated;
grant execute on function public.record_xendit_payment_status(
  uuid,
  text,
  text,
  text,
  numeric,
  timestamptz
) to service_role;

create or replace function public.finalize_xendit_order(
  p_submission_id uuid,
  p_invoice_id text,
  p_external_id text,
  p_paid_amount numeric,
  p_paid_at timestamptz,
  p_payment_method text default null
)
returns table (
  order_id bigint,
  order_number text,
  created boolean
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_payment public.xendit_payments;
  v_pending public.pending_facebook_orders;
  v_order_data jsonb;
  v_created record;
begin
  if p_submission_id is null
    or nullif(p_invoice_id, '') is null
    or nullif(p_external_id, '') is null
    or p_paid_amount is null
    or p_paid_amount <= 0
  then
    raise exception using
      errcode = '22023',
      message = 'paid_invoice_invalid';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_submission_id::text, 0)
  );

  select *
  into v_payment
  from public.xendit_payments
  where submission_id = p_submission_id
  for update;

  if not found then
    raise exception using
      errcode = 'P0002',
      message = 'payment_record_not_found';
  end if;

  if v_payment.xendit_invoice_id <> p_invoice_id
    or v_payment.xendit_external_id <> p_external_id
    or v_payment.amount <> p_paid_amount
  then
    raise exception using
      errcode = '22023',
      message = 'paid_invoice_conflict';
  end if;

  select *
  into v_pending
  from public.pending_facebook_orders
  where id::text = v_payment.order_id
    and submission_id = p_submission_id
  for update;

  if not found then
    raise exception using
      errcode = 'P0002',
      message = 'pending_order_not_found';
  end if;

  v_order_data := v_pending.order_data
    - 'id'
    - 'created_at'
    - 'submission_id'
    - 'order_number_text'
    - 'totalorderprice';

  v_order_data := v_order_data || jsonb_build_object(
    'paymentOption',
    'XENDIT',
    'payment',
    p_paid_amount
  );

  if coalesce(v_order_data->>'facebookname', '') not like '%[PAID VIA XENDIT]%' then
    v_order_data := jsonb_set(
      v_order_data,
      '{facebookname}',
      to_jsonb(
        trim(
          coalesce(v_order_data->>'facebookname', '')
          || ' [PAID VIA XENDIT]'
        )
      ),
      true
    );
  end if;

  select *
  into v_created
  from public.create_order_from_submission(
    p_submission_id,
    v_order_data,
    v_pending.preorder_facebook_u
  );

  update public.xendit_payments
  set
    status = 'PAID',
    paid_amount = p_paid_amount,
    paid_at = coalesce(p_paid_at, now()),
    payment_method = coalesce(p_payment_method, payment_method),
    final_order_id = v_created.order_id,
    updated_at = now()
  where id = v_payment.id;

  update public.pending_facebook_orders
  set
    submission_status = 'completed',
    updated_at = now()
  where id = v_pending.id;

  update public."New PRE Facebook Orders"
  set
    submitted = true,
    submission_status = 'completed',
    submission_updated_at = now()
  where submission_id = p_submission_id
     or (
       v_pending.preorder_facebook_u is not null
       and "facebookU" = v_pending.preorder_facebook_u
     );

  return query
  select
    v_created.order_id,
    v_created.order_number,
    v_created.created;
end;
$$;

revoke execute on function public.finalize_xendit_order(
  uuid,
  text,
  text,
  numeric,
  timestamptz,
  text
) from public, anon, authenticated;
grant execute on function public.finalize_xendit_order(
  uuid,
  text,
  text,
  numeric,
  timestamptz,
  text
) to service_role;

comment on table public.order_submission_events is
  'Privacy-safe order form telemetry. Never store names, contact data, addresses, coordinates, URLs, PSIDs, or provider payloads.';

comment on column public."New Facebook Orders".submission_id is
  'Client-generated idempotency key retained across retries.';

comment on column public.pending_facebook_orders.request_fingerprint is
  'SHA-256 of the normalized server-owned request; contains no raw customer data.';
